//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int idAdmin { get; set; }
        public string loginAdmin { get; set; }
        public string passwordAdmin { get; set; }
        public string number { get; set; }
    }
}
