//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int idEmployee { get; set; }
        public string fullNameEmployee { get; set; }
        public string loginEmployee { get; set; }
        public string passwordEmployee { get; set; }
        public Nullable<int> idPointIssue { get; set; }
        public Nullable<int> number { get; set; }
    
        public virtual PointIssue PointIssue { get; set; }
    }
}
