//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int idOrder { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> idPointIssue { get; set; }
        public Nullable<int> confirmationСode { get; set; }
        public Nullable<bool> statusOrder { get; set; }
    
        public virtual PointIssue PointIssue { get; set; }
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
