//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEStore.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class point
    {
        public int idPointOfIssue { get; set; }
        public string adress { get; set; }
    }
}
